JobWebApp/JobWebApp/Models/ErrorViewModel.cs
using System;

namespace JobWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

JobWebApp/JobWebApp/Models/JobOffer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace JobWebApp.Models
{
    public class JobOffer
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "You must fill the Title field.")]
        [StringLength(50, ErrorMessage = "The {0} must be at least {2} and a maximum of {1} characters.", MinimumLength = 3)]
        public string Title { get; set; }

        [Required(ErrorMessage = "You must fill the City field.")]
        [StringLength(50, ErrorMessage = "The {0} must be at least {2} and a maximum of {1} characters.", MinimumLength = 2)]
        public string Local { get; set; }

        [Required(ErrorMessage = "You must fill the Description field.")]
        [StringLength(300, ErrorMessage = "The {0} must be at least {2} and a maximum of {1} characters.", MinimumLength = 3)]
        public string Description { get; set; }

        [Required(ErrorMessage = "You must fill the Responsibility field.")]
        [StringLength(300, ErrorMessage = "The {0} must be at least {2} and a maximum of {1} characters.", MinimumLength = 3)] 
        public string Responsibility { get; set; }
        
        [Required(ErrorMessage = "You must fill the Requirement field.")]
        [StringLength(300, ErrorMessage = "The {0} must be at least {2} and a maximum of {1} characters.", MinimumLength = 3)]
        public string Requirement { get; set; }

        [Required(ErrorMessage = "You must fill the Post Date field.")]
        [DataType(DataType.Date)]
        [Display(Name = "Post Date")]
        public DateTime PostDate { get; set; }

        [Required(ErrorMessage = "You must fill the Wage field.")]
        public decimal Wage { get; set; }

    }
}

JobWebApp/JobWebApp/Controllers/HomeController.cs
using JobWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace JobWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JobWebApp/JobWebApp/Controllers/JobOffersController.cs
using JobWebApp.Data;
using JobWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JobWebApp.Controllers
{
    public class JobOffersController : Controller
    {

        private readonly AppDbContext _context;

        public JobOffersController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            IEnumerable<JobOffer> listJobOffers = _context.Job;
            return View(listJobOffers);
        }

        // Http Get Create
        public IActionResult Create()
        {
            return View();
        }

        // Http Post Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(JobOffer job)
        {
            if (ModelState.IsValid)
            {
                _context.Job.Add(job);
                _context.SaveChanges();

                TempData["message"] = "The Job Offer has been correctly registred.";
                return RedirectToAction("Index");
            }

            return View();
        }

        // Http Get Edit
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //Obtain the Job
            var job = _context.Job.Find(id);
            if (job == null)
            {
                return NotFound();
            }
            return View(job);
        }

        // Http Post Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(JobOffer job)
        {
            if (ModelState.IsValid)
            {
                _context.Job.Update(job);
                _context.SaveChanges();

                TempData["message"] = "The book has been correctly updated.";
                return RedirectToAction("Index");
            }

            return View();
        }
        // Http Get Delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //Obtain the Job
            var job = _context.Job.Find(id);

            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        // Http Post Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteJob(int? id)
        {
            // obter o job por id
            var job = _context.Job.Find(id);

            if (job == null)
            {
                return NotFound();
            }
            _context.Job.Remove(job);
            _context.SaveChanges();

            TempData["message"] = "The record has been correctly removed.";
            return RedirectToAction("Index");
        }
        
        // Http Get Detail
        public IActionResult Detail(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //Obtain the job
            var job = _context.Job.Find(id);

            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        // Http Get Detail-Temp
        public IActionResult DetailTemp(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            //Obtain the job
            var job = _context.Job.Find(id);

            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }



    }
}

JobWebApp/JobWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Welcome";
}

<body>

    <style>
        Section {
            width: 36rem;
            margin: auto;
            border: 0px solid red;
        }
    </style>

    <div class="text-center">
        <a class="nav-link text-dark" asp-controller="JobOffers" asp-action="Index"> <h1 class="display-4">Welcome</h1></a>
        <a class="nav-link text-dark" asp-controller="JobOffers" asp-action="Index"> To initiate the App clik here</a>
    </div>
    <Section>
        <div class="card border-primary mb-3" style="max-width: 36rem;" margin-left="auto" margin-right="auto">
            <div class="card-header">Task</div>
            <div class="card-body">
                <h4 class="card-title">Develop an Application to controll Job Offers</h4>
                <p class="card-text"> Web Application com cadastrar, visualizar, deletar e editar vagas de trabalho:</p>
                <p>- Linguagem: .NET (Framework ou Core)</p>
                <p>- Arquitetura: MVC (ASP.NET MVC)</p>
                <p>- Armazenamento: Banco de dados</p>
                <p></p>
                <p>- Aparência não é um fator de avaliação</p>
            </div>
        </div>

        <div class="card border-primary mb-3" style="max-width: 36rem;">
            <div class="card-header">Solution</div>
            <div class="card-body">
                <h4 class="card-title">Developed a CRUD with ASP.NET 5.0</h4>
                <p class="card-text">With: </p>
                <p>- Microsoft Visual Studio</p>
                <p>- Database SqlServer</p>
            </div>
        </div>
    </Section>
</body>

JobWebApp/JobWebApp/Views/JobOffers/Create.cshtml
@model JobWebApp.Models.JobOffer
@{
    ViewData["Title"] = "Create a New Job Offer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    <div class="row">
        <div class="col-sm-12">
            <h3>Create a New Job Offer</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control"></>
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Local" class="control-label"></label>
                    <input asp-for="Local" class="form-control"></>
                    <span asp-validation-for="Local" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control"></>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Responsibility" class="control-label"></label>
                    <input asp-for="Responsibility" class="form-control"></>
                    <span asp-validation-for="Responsibility" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Requirement" class="control-label"></label>
                    <input asp-for="Requirement" class="form-control"></>
                    <span asp-validation-for="Requirement" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="PostDate" class="control-label"></label>
                    <input asp-for="PostDate" class="form-control"></>
                    <span asp-validation-for="PostDate" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Wage" class="control-label"></label>
                    <input asp-for="Wage" class="form-control"></>
                    <span asp-validation-for="Wage" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <span></span>
                    <a asp-controller="JobOffers" asp-action="Index" class="btn btn-success"> Return without create</a>
                    <input type="submit" value="Create Record" class="btn btn-primary"></>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

JobWebApp/JobWebApp/Views/JobOffers/Delete.cshtml
@model JobWebApp.Models.JobOffer
@{
    ViewData["Title"] = "Delete a Job Offer Record";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    <div class="row">
        <div class="col-sm-12">
            <h3>Delete a Job Offer Record</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="DeleteJob">
                <input type="hidden" asp-action="Id" />

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" disabled />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Local" class="control-label"></label>
                    <input asp-for="Local" class="form-control" disabled />
                    <span asp-validation-for="Local" class="text-danger"></span>
                </div>
                
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" disabled />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>                
                
                <div class="form-group">
                    <label asp-for="Responsibility" class="control-label"></label>
                    <input asp-for="Responsibility" class="form-control" disabled />
                    <span asp-validation-for="Responsibility" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Requirement" class="control-label"></label>
                    <input asp-for="Requirement" class="form-control" disabled />
                    <span asp-validation-for="Requirement" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="PostDate" class="control-label"></label>
                    <input asp-for="PostDate" class="form-control" disabled />
                    <span asp-validation-for="PostDate" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Wage" class="control-label"></label>
                    <input asp-for="Wage" class="form-control" disabled />
                    <span asp-validation-for="Wage" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <p><span></span></p>
                    <a asp-controller="JobOffers" asp-action="Index" class="btn btn-success"> Return without delet</a>
                    <input type="submit" value="Delete" class="btn btn-danger"></>
                    
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

JobWebApp/JobWebApp/Views/JobOffers/Detail.cshtml
@model JobWebApp.Models.JobOffer
@{
    ViewData["Title"] = "Detail of a Job Offer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    <div class="row">
        <div class="col-sm-12">
            <h3>Details of a Job Offer</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Detail">

                <input type="hidden" asp-action="Id" />

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" disabled />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Local" class="control-label"></label>
                    <input asp-for="Local" class="form-control" disabled />
                    <span asp-validation-for="Local" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" disabled />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Responsibility" class="control-label"></label>
                    <input asp-for="Responsibility" class="form-control" disabled />
                    <span asp-validation-for="Responsibility" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Requirement" class="control-label"></label>
                    <input asp-for="Requirement" class="form-control" disabled />
                    <span asp-validation-for="Requirement" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="PostDate" class="control-label"></label>
                    <input asp-for="PostDate" class="form-control" disabled />
                    <span asp-validation-for="PostDate" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Wage" class="control-label"></label>
                    <input asp-for="Wage" class="form-control" disabled />
                    <span asp-validation-for="Wage" class="text-danger"></span>
                </div>
            </form>
        </div>
    </div>
</div>

<td>
    <p><span></span></p>
    <a asp-controller="JobOffers" asp-action="Index" class="btn btn-success"> Return</a>

</td>


@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

JobWebApp/JobWebApp/Views/JobOffers/DetailTemp.cshtml
@model JobWebApp.Models.JobOffer
@{
    ViewData["Title"] = "Job Offer Application";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    @if (TempData["message"] != null)
    {
        <div class="alert alert-dismissible alert-info fade show" role="alert">
            <strong>@TempData["message"]</strong>
            <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"></span>
            </button>
        </div>
    }

    <div class="row">
        <div class="col-sm-6">
            <h3>Job Offer Application</h3>
        </div>
        <div class="col-sm-6">
            <a class="btn btn-dark d-block" asp-action="Create" asp-controller="JobOffers">Create New Job Offer Record</a>
        </div>
    </div>
    <div class="row">
       
        <table class="table table-bordered table-striped ">
            <thead>
                   
            </thead>                             
                
            <tbody>
                <tr><td>@Html.DisplayNameFor(m => m.Id) item.Id</td></tr>
                <tr><td>@Html.DisplayNameFor(m => m.Title) item.Title</td></tr>
                <tr><td>@Html.DisplayNameFor(m => m.Local) item.Local</td></tr>
                <tr><td>@Html.DisplayNameFor(m => m.PostDate) item.PostDate.ToString("d")</td></tr>
                <tr><td>@Html.DisplayNameFor(m => m.Wage) item.Wage</td></tr>
                <tr><td>@Html.DisplayNameFor(m => m.Description) item.Description</td></tr>
                <tr><td>@Html.DisplayNameFor(m => m.Responsibility) item.Responsibility</td></tr>
                <tr><td>@Html.DisplayNameFor(m => m.Requirement) item.Requirement</td></tr>
                    @*<td>
                    <a asp-controller="JobOffers" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning"> Edit</a>
                    <a asp-controller="JobOffers" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger"> Delete</a>
                    <a asp-controller="JobOffers" asp-action="Detail" asp-route-id="@item.Id" class="btn btn-success"> Detail</a>
                    </td>*@
            </tbody>
        </table>
        
    </div>
</div>

JobWebApp/JobWebApp/Views/JobOffers/Edit.cshtml
@model JobWebApp.Models.JobOffer
@{
    ViewData["Title"] = "Edit a Job Offer Record";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    <div class="row">
        <div class="col-sm-12">
            <h3>Edit a Job Offer Record</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Edit">
                <input type="hidden" asp-action="Id" />

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control"></>
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Local" class="control-label"></label>
                    <input asp-for="Local" class="form-control"></>
                    <span asp-validation-for="Local" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control"></>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Responsibility" class="control-label"></label>
                    <input asp-for="Responsibility" class="form-control"></>
                    <span asp-validation-for="Responsibility" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Requirement" class="control-label"></label>
                    <input asp-for="Requirement" class="form-control"></>
                    <span asp-validation-for="Requirement" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="PostDate" class="control-label"></label>
                    <input asp-for="PostDate" class="form-control"></>
                    <span asp-validation-for="PostDate" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Wage" class="control-label"></label>
                    <input asp-for="Wage" class="form-control"></>
                    <span asp-validation-for="Wage" class="text-danger"></span>
                </div>

                <div class="row">
                    <div class="form-group">
                        <p><span></span></p>
                        <a asp-controller="JobOffers" asp-action="Index" class="btn btn-success"> Return without any change</a>
                        <input type="submit" value="Update" class="btn btn-primary"></>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

JobWebApp/JobWebApp/Views/JobOffers/Index.cshtml
@model IEnumerable<JobWebApp.Models.JobOffer>
@{
    ViewData["Title"] = "Job Offer Application";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    @if (TempData["message"] != null)
    {
        <div class="alert alert-dismissible alert-info fade show" role="alert">
            <strong>@TempData["message"]</strong>
            <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"></span>
            </button>
        </div>
    }

    <div class="row">
        <div class="col-sm-6">
            <h3>Job Offer Application</h3>
        </div>
        <div class="col-sm-6">
            <a class="btn btn-dark d-block" asp-action="Create" asp-controller="JobOffers">Create New Job Offer Record</a>
        </div>
    </div>
    <div class="row">
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered table-striped ">
                <thead>
                    <tr>
                        <td>@Html.DisplayNameFor(m => m.Id)</td>
                        <td>@Html.DisplayNameFor(m => m.Title)</td>
                        <td>@Html.DisplayNameFor(m => m.Local)</td>
                        <td>@Html.DisplayNameFor(m => m.PostDate)</td>
                        <td>@Html.DisplayNameFor(m => m.Wage)</td>
                        
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Title</td>
                            <td>@item.Local</td>
                            <td>@item.PostDate.ToString("d")</td>
                            <td>@item.Wage</td>
                            <td>

                            <td>
                                <a asp-controller="JobOffers" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning"> Edit</a>
                                <a asp-controller="JobOffers" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger"> Delete</a>
                                <a asp-controller="JobOffers" asp-action="Detail" asp-route-id="@item.Id" class="btn btn-success"> Detail</a>
                            </td>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>There are no records!</p>
        }
    </div>
</div>

JobWebApp/JobWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JobWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-Flatly.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">JobWebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="JobOffers" asp-action="Index"> Crud JobApp</a>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - JobWebApp - Luis Martins
            @*<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>